#!/bin/sh
# live-build configuration for KnucklsOS (Debian-based, reliably automated)
set -e

lb config noauto \
    --mode debian \
    --distribution bookworm \
    --architectures amd64 \
    --archive-areas "main contrib non-free non-free-firmware" \
    --parent-archive-areas "main contrib non-free non-free-firmware" \
    --apt-indices false \
    --apt-recommends true \
    --binary-images iso-hybrid \
    --bootappend-live "boot=live components quiet splash live-user=knucklsos" \
    --bootappend-live-failsafe "boot=live components memtest noapic noapm nodma nomce nolapic nomodeset nosmp nosplash vga=788 live-user=knucklsos" \
    --linux-packages "linux-image-amd64" \
    --initramfs-compression gzip \
    --image-name knucklsos \
    --iso-application "KnucklsOS" \
    --iso-publisher "KnucklsOS Project" \
    --iso-volume "KnucklsOS" \
    --checksums sha256 \
    "$@"
